package dev.riftgun.network;

public enum PortalAction {
    OPEN_GUI,
    OPEN_MODULES,
    CREATE_CURRENT,
    CREATE_COORDINATE,
    EDIT_DESTINATION,
    DELETE_DESTINATION,
    TOGGLE_PIN,
    VIEW_DESTINATION,
    SELECT_DESTINATION,
    SELECT_PLAYER,
    OPEN_PORTAL,
    OPEN_SELECTED,
    CYCLE_PLACEMENT_MODE,
    CREATE_GROUP,
    RENAME_GROUP,
    DELETE_GROUP,
    MOVE_GROUP,
    MOVE_DESTINATION_GROUP,
    SET_GROUP_EXPANDED,
    SET_SETTINGS,
    SET_GUN_MODULE_SETTINGS,
    TOGGLE_BUCKET_MODE,
    CLEAR_GUN_FLUID,
    REQUEST_PLAYERS,
    OPEN_PLAYER_PORTAL,
    TOGGLE_PLAYER_PIN,
    CLOSE_PORTALS,
    SET_PRIVACY,
    SET_PRIVACY_OVERRIDE,
    REQUEST_PRIVACY_PLAYERS;

    public boolean requiresPortalGun() {
        return switch (this) {
            case SET_PRIVACY, SET_PRIVACY_OVERRIDE, REQUEST_PRIVACY_PLAYERS -> false;
            default -> true;
        };
    }
}
