package dev.riftgun.network;

public enum PortalAction {
    OPEN_GUI,
    CREATE_CURRENT,
    CREATE_COORDINATE,
    EDIT_DESTINATION,
    DELETE_DESTINATION,
    TOGGLE_PIN,
    VIEW_DESTINATION,
    SELECT_DESTINATION,
    OPEN_PORTAL,
    OPEN_SELECTED,
    CYCLE_PLACEMENT_MODE,
    CHECK_SAFETY,
    CREATE_GROUP,
    RENAME_GROUP,
    DELETE_GROUP,
    MOVE_GROUP,
    SET_GROUP_EXPANDED,
    SET_SETTINGS
}
