package dev.riftgun.module;

public enum PortalModuleKind {
    COORDINATE_OVERRIDE,
    RESERVOIR_EXPANSION,
    PASSIVE_TRANSIT,
    HOSTILE_TRANSIT,
    BOSS_TRANSIT,
    SURFACE_RANGE,
    APERTURE_EXPANSION,
    MODULE_BAY_EXPANSION,
    PLAYER_TARGET,
    DURATION_EXTENSION,
    DURATION_ETERNAL,
    FALL_GUARD
}
