minecraft_version=1.21.1
neoforge_version=21.1.140
jei_version=19.21.1.248
immersive_portals_version=6.0.7
lambdynamiclights_version=4.8.10+1.21.1
java_version=21
journeymap_api_version=2.0.0-1.21.1
xaero_minimap_artifact=xaerominimap-neoforge-1.21.1
xaero_minimap_version=26.4.2
mod_version=0.2.0-rc.1
